from __future__ import annotations

import argparse
import sys
from pathlib import Path

from rich.console import Console

ROOT_DIR = Path(__file__).resolve().parents[1]
JOBS_DIR = Path(__file__).resolve().parent
SET_DIST_DIR = ROOT_DIR / "set_distribution"

if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))
if str(JOBS_DIR) not in sys.path:
    sys.path.insert(0, str(JOBS_DIR))

from train_utils import build_model_name, get_job_id, load_predefined_split

from src.Cli.config import MODELS_DIR
from src.Cli.training import TrainingSession

"""
Train a single classical ML model (KNN / RandomForest / SVM) on the SpO2 feature files. Uses a predefined train/test/validate split defined in set_distribution/training_set.txt and test_set.txt, which should be generated by running jobs/generate_sets.py.
params:
    --model: Which classifier to train (required).
    --records: Optional whitelist of record IDs. When given, only these records are used from training_set.txt.
    --set-dist-dir: Directory containing training_set.txt and test_set.txt. Defaults to <root>/set_distribution/.
    --normalized / --no-normalized: Use normalised feature files when available (default: normalised).
    --n-neighbors: [KNN] Number of neighbours (default: 5).
    --n-estimators: [RandomForest] Number of trees (default: 100).
    --max-depth: [RandomForest] Maximum tree depth (default: 10).
    --C: [SVM] Regularisation parameter C for LinearSVC (default: 1.0).
    --model-name: Output model name without extension. Defaults to a descriptive timestamped name.
    --no-save: Skip writing the model checkpoint and metadata sidecar.
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a classical ML model (KNN / RandomForest / SVM) on SpO2 feature files."
    )
    parser.add_argument(
        "--model",
        required=True,
        choices=["KNN", "RandomForest", "SVM"],
        help="Which classifier to train.",
    )
    parser.add_argument(
        "--records",
        nargs="+",
        help="Optional whitelist of record IDs. When given, only these records are used from training_set.txt.",
    )
    parser.add_argument(
        "--set-dist-dir",
        type=Path,
        default=None,
        help="Directory containing training_set.txt and test_set.txt. Defaults to <root>/set_distribution/.",
    )
    parser.add_argument(
        "--normalized",
        action="store_true",
        default=True,
        help="Use normalised feature files when available (default: true).",
    )
    parser.add_argument(
        "--no-normalized",
        dest="normalized",
        action="store_false",
        help="Use raw (non-normalised) feature files.",
    )

    # --- KNN ---
    parser.add_argument(
        "--n-neighbors",
        type=int,
        default=5,
        help="[KNN] Number of neighbours (default: 5).",
    )

    # --- RandomForest ---
    parser.add_argument(
        "--n-estimators",
        type=int,
        default=100,
        help="[RandomForest] Number of trees (default: 100).",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=10,
        help="[RandomForest] Maximum tree depth (default: 10).",
    )

    # --- SVM ---
    parser.add_argument(
        "--C",
        type=float,
        default=1.0,
        help="[SVM] Regularisation parameter C for LinearSVC (default: 1.0).",
    )

    # --- Common ---
    parser.add_argument(
        "--model-name",
        default=None,
        help="Output model name without extension. Defaults to a descriptive timestamped name.",
    )
    parser.add_argument(
        "--no-save",
        action="store_true",
        help="Skip writing the model checkpoint and metadata sidecar.",
    )
    return parser.parse_args()


def build_model(args: argparse.Namespace):
    """Instantiate the requested model and return (model, hyperparams_dict)."""
    if args.model == "KNN":
        from src.Models.KNN import KNN

        hyperparams = {"n_neighbors": args.n_neighbors}
        return KNN(**hyperparams), hyperparams

    if args.model == "RandomForest":
        from src.Models.RandomForest import RandomForest

        hyperparams = {
            "n_estimators": args.n_estimators,
            "max_depth": args.max_depth,
        }
        return RandomForest(**hyperparams), hyperparams

    if args.model == "SVM":
        from src.Models.SVM import SVM

        hyperparams = {"C": args.C}
        return SVM(**hyperparams), hyperparams

    raise ValueError(f"Unknown model: {args.model}")


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")

    args = parse_args()
    console = Console()
    session = TrainingSession(console)

    try:
        set_dist_dir = args.set_dist_dir if args.set_dist_dir else SET_DIST_DIR
        all_records = session.find_records_with_features()
        available = {r["name"] for r in all_records if r["has_labels"]}

        train_records, test_records, validation_records = load_predefined_split(
            available, set_dist_dir, args.records
        )
        # Validation records are not used for classical models, add to training and ignore validation split
        train_records = train_records + validation_records
        console.print(
            f"[cyan]Train:[/cyan] {len(train_records)} record(s)  "
            f"[cyan]Test:[/cyan] {len(test_records)} record(s)"
        )
        console.print(
            f"[dim]Normalised features: {'yes' if args.normalized else 'no'}[/dim]"
        )
        X_train, y_train, feature_names = session.build_dataset(
            train_records, use_normalized=args.normalized
        )
        X_test, y_test, _ = session.build_dataset(
            test_records, use_normalized=args.normalized
        )

        model, hyperparams = build_model(args)
        hyperparams["use_normalized"] = args.normalized

        session.train(model, X_train, y_train)
        metrics = session.evaluate(model, X_test, y_test)

        if not args.no_save:
            model_name = build_model_name(args)
            job_id = get_job_id()
            output_dir = MODELS_DIR / "batch" / job_id
            output_path = session.save_model(
                model,
                model_name,
                output_dir,
                hyperparams=hyperparams,
                metrics=metrics,
                records=train_records,
                feature_names=feature_names,
            )
            console.print(f"[green]Saved model:[/green] {output_path}")
            console.print(f"[dim]Job ID:[/dim] {job_id}")
        else:
            console.print("[yellow]Skipping model save (--no-save).[/yellow]")

        console.print("[green]Training run finished successfully.[/green]")
        return 0

    except Exception as exc:
        console.print(f"[red]Training failed:[/red] {exc}")
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
